spring:
  application:
    name: movie

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=movie
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: mamedovelchin6@gmail.com
    password: kiwarefhcishoxqu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      debug: true


  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  h2:
    console:
      path: /h2-console
      enabled: true

jwt:
  secret: yoBLl6KR5te3Pow3qsFG5T19TZFzPV2w/8s+2xhbfKACQT1hv+YdxV9l4QMdxExsa2hm0VBb17MEfW0QOVHttA==




