spring:
  application:
    name: movie

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      debug: true


  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
      enabled: true



frontend:
  url: ${FRONTEND_URL}

jwt:
  secret: ${JWT_SECRET_KEY}


cloud:
  aws:
    region:
      static: ${AWS_REGION}
    bucket:
      name: ${AWS_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}


